networks:
  dns-net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.9.0.0/24
services:
  attacker:
    cap_add:
    - ALL
    command: tail -f /dev/null
    container_name: attacker
    image: bind9-base
    networks:
      dns-net:
        ipv4_address: 10.9.0.10
    tty: true
    volumes:
    - ./Attacks:/attacks
  attacker-dns:
    cap_add:
    - ALL
    command: /bin/bash -c "named -g"
    container_name: attacker-dns
    image: bind9-base
    networks:
      dns-net:
        ipv4_address: 10.9.0.155
    volumes:
    - ./config/attacker-dns:/etc/bind
  root-dns:
    cap_add:
    - ALL
    command: /bin/bash -c "named -g"
    container_name: root-dns
    image: bind9-base
    networks:
      dns-net:
        ipv4_address: 10.9.0.153
    volumes:
    - ./config/root-dns:/etc/bind
  example-dns:
    cap_add:
    - ALL
    command: /bin/bash -c "tc qdisc add dev eth0 root netem delay 2000ms && named
      -g"
    container_name: example-dns
    image: bind9-base
    networks:
      dns-net:
        ipv4_address: 10.9.0.154
    volumes:
    - ./config/example-dns:/etc/bind
  local-dns:
    build: ./bind8
    cap_add:
    - ALL
    command: /bin/bash -c "named -b /etc/bind/named.boot && tail -f /dev/null"
    container_name: local-dns
    image: bind8-base
    networks:
      dns-net:
        ipv4_address: 10.9.0.53
    volumes:
    - ./config/local-dns:/etc/bind
    - ./config/resolv.conf:/etc/resolv.conf:ro
  victim:
    cap_add:
    - ALL
    command: tail -f /dev/null
    container_name: victim
    image: bind9-base
    networks:
      dns-net:
        ipv4_address: 10.9.0.20
    tty: true
version: '3.8'
