options {
    directory "/etc/bind";
    recursion yes;
    allow-query { any; };
    dnssec-validation no;
    #dnssec-enable yes;
    query-source port 33333; 
};

zone "." {
    type hint;
    file "/etc/bind/db.root";
};

#trusted-keys {
#    example.com. 257 3 5 "KEY_VALUE_HERE";
#};