options {
    directory "/etc/bind";
    recursion yes;
    allow-query { any; };
    dnssec-validation no;
    query-source port 33333; 
};

zone "." {
    type hint;
    file "/etc/bind/db.root";
};
